/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                navy: {
                    50: '#e6eaf0',
                    100: '#c0c9d9',
                    200: '#97a5bf',
                    300: '#6d81a5',
                    400: '#4d6691',
                    500: '#2d4b7e',
                    600: '#274276',
                    700: '#1f376a',
                    800: '#172c5e',
                    900: '#0a1628',
                    950: '#050d1a',
                },
                cyan: {
                    DEFAULT: '#00e5ff',
                    50: '#e0fbff',
                    100: '#b3f5ff',
                    200: '#80eeff',
                    300: '#4de7ff',
                    400: '#26e2ff',
                    500: '#00e5ff',
                    600: '#00c4d9',
                    700: '#009eb3',
                    800: '#00798c',
                    900: '#004d5e',
                },
                amber: {
                    DEFAULT: '#ffb300',
                    50: '#fff8e1',
                    100: '#ffecb3',
                    200: '#ffe082',
                    300: '#ffd54f',
                    400: '#ffca28',
                    500: '#ffb300',
                    600: '#ffa000',
                    700: '#ff8f00',
                    800: '#ff6f00',
                    900: '#e65100',
                },
            },
            fontFamily: {
                sora: ['Sora', 'sans-serif'],
                dm: ['"DM Sans"', 'sans-serif'],
            },
            backdropBlur: {
                xs: '2px',
            },
            animation: {
                'fade-in': 'fadeIn 0.5s ease-out',
                'slide-up': 'slideUp 0.5s ease-out',
                'slide-in-right': 'slideInRight 0.3s ease-out',
                'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
                'spin-slow': 'spin 3s linear infinite',
                'bounce-in': 'bounceIn 0.6s ease-out',
                'scale-in': 'scaleIn 0.3s ease-out',
                'float': 'float 3s ease-in-out infinite',
            },
            keyframes: {
                fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
                slideUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
                slideInRight: { '0%': { opacity: '0', transform: 'translateX(20px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
                pulseGlow: { '0%, 100%': { boxShadow: '0 0 5px rgba(0,229,255,0.3)' }, '50%': { boxShadow: '0 0 20px rgba(0,229,255,0.6)' } },
                bounceIn: { '0%': { transform: 'scale(0.3)', opacity: '0' }, '50%': { transform: 'scale(1.05)' }, '70%': { transform: 'scale(0.9)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
                scaleIn: { '0%': { transform: 'scale(0.9)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
                float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-10px)' } },
            },
        },
    },
    plugins: [],
}
